name: Build Zipapp

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Python Release]
    types: [completed]

permissions:
  contents: read

jobs:
  build-cli:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Build & Test
        run: |
          python --version
          pip install poetry
          python -m venv .venv
          poetry build
          pip install -q --target pack --no-compile --upgrade dist/*.whl
          python -m zipapp pack -o ./qubership_pipelines_modules_ops.pyz --main=qubership_pipelines_modules_ops.__main__:cli --compress
          echo "RELEASE_VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Upload Assets to Release
        uses: netcracker/qubership-workflow-hub/actions/archive-and-upload-assets@main
        with:
          ref: "v${{ env.RELEASE_VERSION }}"
          config-path: "./.github/assets-config.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}